/**
 * Fetches one unique Unsplash image per blog post and outputs a slug→URL map.
 * Run: node scripts/fetch-images.mjs
 * Requires UNSPLASH_ACCESS_KEY in .env.local
 */

import { readFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dir = dirname(fileURLToPath(import.meta.url));
const root = join(__dir, "..");

// Read .env.local
const envRaw = readFileSync(join(root, ".env.local"), "utf8");
const envVars = Object.fromEntries(
  envRaw
    .split("\n")
    .filter((l) => l.includes("="))
    .map((l) => l.split("=").map((s) => s.trim()))
);
const ACCESS_KEY = envVars["UNSPLASH_ACCESS_KEY"];
if (!ACCESS_KEY) throw new Error("UNSPLASH_ACCESS_KEY not found in .env.local");

// Extract all posts (slug + unsplashQuery) from the three post files
function extractPosts(filename) {
  const text = readFileSync(join(root, "lib", filename), "utf8");
  const posts = [];
  const slugRe = /slug:\s*"([^"]+)"/g;
  const queryRe = /unsplashQuery:\s*"([^"]+)"/g;
  let sm, qm;
  const slugs = [];
  const queries = [];
  while ((sm = slugRe.exec(text))) slugs.push(sm[1]);
  while ((qm = queryRe.exec(text))) queries.push(qm[1]);
  for (let i = 0; i < slugs.length; i++) {
    posts.push({ slug: slugs[i], query: queries[i] ?? "couple sleep" });
  }
  return posts;
}

const allPosts = [
  ...extractPosts("posts118.ts"),
  ...extractPosts("posts1936.ts"),
  ...extractPosts("posts3752.ts"),
];

console.log(`Fetching images for ${allPosts.length} posts...`);

// Fetch unique image for each post — stagger requests to avoid rate limit
const results = {};
const usedPhotoIds = new Set();

for (let i = 0; i < allPosts.length; i++) {
  const { slug, query } = allPosts[i];
  let attempts = 0;
  let url = null;
  let photoId = null;

  while (attempts < 5) {
    const page = Math.floor(Math.random() * 5) + 1;
    const res = await fetch(
      `https://api.unsplash.com/photos/random?query=${encodeURIComponent(query)}&count=1&orientation=landscape`,
      { headers: { Authorization: `Client-ID ${ACCESS_KEY}` } }
    );

    if (!res.ok) {
      console.error(`  [${i + 1}] ${slug}: HTTP ${res.status}`);
      break;
    }

    const data = await res.json();
    const photo = Array.isArray(data) ? data[0] : data;
    photoId = photo?.id;
    const rawUrl = photo?.urls?.regular;

    if (rawUrl && !usedPhotoIds.has(photoId)) {
      // Clean URL — keep only essential params for caching
      url = `${rawUrl.split("?")[0]}?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080`;
      usedPhotoIds.add(photoId);
      break;
    }
    attempts++;
    // Brief pause between retries
    await new Promise((r) => setTimeout(r, 200));
  }

  if (url) {
    results[slug] = url;
    console.log(`  [${i + 1}/${allPosts.length}] ✓ ${slug}`);
  } else {
    // Fallback: use index-based pool image
    const FALLBACK = [
      "https://images.unsplash.com/photo-1570657569068-203890a3aa2f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
      "https://images.unsplash.com/photo-1560863185-a4f6199b5768?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
      "https://images.unsplash.com/photo-1611690825764-583a6127d4fe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    ];
    results[slug] = FALLBACK[i % FALLBACK.length];
    console.log(`  [${i + 1}/${allPosts.length}] ⚠ ${slug} — used fallback`);
  }

  // Rate limit: Unsplash Demo allows 50 req/hour, Production 5000/hour
  // Add a small delay between requests to be safe
  await new Promise((r) => setTimeout(r, 150));
}

// Output the map as a TypeScript const — paste into lib/posts.ts
const output = `// Auto-generated by scripts/fetch-images.mjs — do not edit manually
export const POST_IMAGES: Record<string, string> = ${JSON.stringify(results, null, 2)};
`;

import { writeFileSync } from "fs";
writeFileSync(join(root, "lib", "post-images.ts"), output);
console.log(`\nDone! Wrote lib/post-images.ts with ${Object.keys(results).length} unique image URLs.`);
